Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,9 +1,9 @@
-name: Deploy React App to EC2
+name: Deploy Vite App to EC2
 
 on:
   push:
     branches:
-      - dev
+      - main
 
 jobs:
   deploy:
@@ -27,8 +27,8 @@ jobs:
         run: |
           echo "Root directory contents:"
           ls -la
-          echo "Build directory contents:"
-          ls -la build || { echo "❌ Build folder missing!"; exit 1; }
+          echo "Dist directory contents:"
+          ls -la dist || { echo "❌ Dist folder missing!"; exit 1; }
 
       - name: Prepare EC2 directory
         uses: appleboy/ssh-action@v1.0.0
@@ -40,7 +40,7 @@ jobs:
             sudo mkdir -p /var/www/frontend
             sudo rm -rf /var/www/frontend/*
 
-      - name: Upload build files
+      - name: Upload dist files
         uses: appleboy/scp-action@v0.1.3
         with:
           host: ${{ secrets.EC2_HOST }}
