Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,8 +25,10 @@ jobs:
 
       - name: Verify build output
         run: |
+          echo "Root directory contents:"
           ls -la
-          ls -la build || echo "No build folder found!"
+          echo "Build directory contents:"
+          ls -la build || { echo "❌ Build folder missing!"; exit 1; }
 
       - name: Prepare EC2 directory
         uses: appleboy/ssh-action@v1.0.0
@@ -35,9 +37,8 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            rm -rf /var/www/frontend/*
-            mkdir -p /var/www/frontend
-            sudo mkdir /var/www/frontendtttt
+            sudo mkdir -p /var/www/frontend
+            sudo rm -rf /var/www/frontend/*
 
       - name: Upload build files
         uses: appleboy/scp-action@v0.1.3
@@ -45,5 +46,5 @@ jobs:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
-          source: "build/*"
+          source: "build/"
           target: "/var/www/frontend"
